# Generated by Django 5.0.6 on 2024-07-12 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_casestudy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
