# Generated by Django 5.0.6 on 2024-07-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
    ]
