# Generated by Django 5.0.6 on 2024-07-17 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_company_image_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='sub_service/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.service')),
            ],
        ),
    ]
