# Generated by Django 4.2.9 on 2024-08-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_company_name_alter_company_image'),
        ('apis', '0008_subservice'),
    ]

    operations = [
    ]
