# Generated by Django 5.0.6 on 2024-08-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_merge_20240822_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
    ]
